kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
spec:
  replicas: 4
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      name: whoami
      labels:
        app: whoami
        env: prod
    spec:
      containers:
      - name: whoami
        image: acrdemo77.azurecr.io/whoami:v1
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: dupa1-auth

kind: Service
apiVersion: v1
metadata:
  name: whoami
  labels:
    name: whoami
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8000
    protocol: TCP
  selector:
    app: whoami
